apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-security-scanner-role
  labels:
    app: cloud-security-scanner
    role: security-audit
rules:
# Core Kubernetes resources - read only for security auditing
- apiGroups: [""]
  resources: 
    - "pods"
    - "services" 
    - "endpoints"
    - "persistentvolumeclaims"
    - "events"
    - "configmaps"
    - "secrets"
    - "namespaces"
    - "nodes"
    - "serviceaccounts"
  verbs: ["get", "list", "watch"]

# Apps resources
- apiGroups: ["apps"]
  resources: 
    - "deployments"
    - "daemonsets" 
    - "replicasets"
    - "statefulsets"
  verbs: ["get", "list", "watch"]

# Batch resources
- apiGroups: ["batch"]
  resources: 
    - "jobs"
    - "cronjobs"
  verbs: ["get", "list", "watch"]

# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources: 
    - "networkpolicies"
    - "ingresses"
  verbs: ["get", "list", "watch"]

# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: 
    - "roles"
    - "rolebindings"
    - "clusterroles"
    - "clusterrolebindings"
  verbs: ["get", "list", "watch"]

# Policy resources
- apiGroups: ["policy"]
  resources: 
    - "podsecuritypolicies"
    - "poddisruptionbudgets"
  verbs: ["get", "list", "watch"]

# Storage resources
- apiGroups: ["storage.k8s.io"]
  resources: 
    - "storageclasses"
    - "volumeattachments"
  verbs: ["get", "list", "watch"]

# Autoscaling resources
- apiGroups: ["autoscaling"]
  resources: 
    - "horizontalpodautoscalers"
  verbs: ["get", "list", "watch"]

# Metrics resources (if available)
- apiGroups: ["metrics.k8s.io"]
  resources: 
    - "pods"
    - "nodes"
  verbs: ["get", "list"]