apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-security-scanner-role
  labels:
    app: cloud-security-scanner
    platform: openshift
rules:
# Standard Kubernetes resources
- apiGroups: [""]
  resources: 
    - "pods"
    - "services"
    - "endpoints"
    - "persistentvolumeclaims"
    - "events"
    - "configmaps"
    - "secrets"
    - "namespaces"
  verbs: ["get", "list", "watch"]

# Apps resources
- apiGroups: ["apps"]
  resources: 
    - "deployments"
    - "daemonsets"
    - "replicasets"
    - "statefulsets"
  verbs: ["get", "list", "watch"]

# OpenShift specific resources
- apiGroups: ["route.openshift.io"]
  resources: 
    - "routes"
  verbs: ["get", "list", "watch"]

- apiGroups: ["image.openshift.io"]
  resources: 
    - "imagestreams"
    - "imagestreamimages"
    - "imagestreamtags"
  verbs: ["get", "list", "watch"]

- apiGroups: ["build.openshift.io"]
  resources: 
    - "builds"
    - "buildconfigs"
  verbs: ["get", "list", "watch"]

- apiGroups: ["security.openshift.io"]
  resources: 
    - "securitycontextconstraints"
  verbs: ["get", "list", "watch"]

- apiGroups: ["project.openshift.io"]
  resources: 
    - "projects"
  verbs: ["get", "list", "watch"]

- apiGroups: ["user.openshift.io"]
  resources: 
    - "users"
    - "groups"
  verbs: ["get", "list", "watch"]

- apiGroups: ["oauth.openshift.io"]
  resources: 
    - "oauthclients"
  verbs: ["get", "list", "watch"]